# src/routes/swagger.yaml 

openapi: 3.0.0
info:
  title: PolyTales API
  version: 1.0.0
  description: 언어학습 스토리 및 노트 관리 API

paths:
  /stories:
    get:
      summary: 전체 스토리 조회
      parameters:
        - in: query
          name: level
          schema:
            type: string
        - in: query
          name: topic
          schema:
            type: string
      responses:
        '200':
          description: 스토리 목록 반환

  /stories/{id}:
    get:
      summary: 특정 스토리 조회
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer

  /stories/level/{level}:
    get:
      summary: 레벨별 스토리 조회
      parameters:
        - in: path
          name: level
          required: true
          schema:
            type: string

  /notes:
    post:
      summary: 노트 생성
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                userid:
                  type: integer
                storyid:
                  type: integer
                title:
                  type: string
                content:
                  type: string
              required:
                - userid
                - storyid
                - title
                - content

  /notes/{userid}:
    get:
      summary: 사용자별 노트 조회
      parameters:
        - in: path
          name: userid
          required: