# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: polytales backend

on:
  push:
    branches: [main]
    paths:
      - 'back/**'
      - '.github/workflows/back.yml'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    defaults:
      run:
        working-directory: back

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'
          cache-dependency-path: back/package-lock.json

      - name: Install
        run: npm ci

      - name: Build (optional)
        run: npm run build --if-present

      - name: Test (optional)
        run: npm test --if-present

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: back
          path: back

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: back
          path: back

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_6F413C7AB98D4C169C51ABC227BCC67F }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_0FFFBAAD7F444C518EADA8E6520AF7DB }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_1A070CA010DF4C5CB9F386EB8A09A3FB }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'polytales'   # App Service 이름 정확히 일치
          package: back           # 아티팩트로 받은 back 폴더만 배포
