name: polytales frontend

on:
  push:
    branches: [ main ]
    paths:
      - 'polytales-fe/**'
      - '.github/workflows/front.yml'
  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # OIDC 단계는 생략 가능 (토큰 인증만 사용)
      - name: Build & Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_BLUE_FLOWER_03F832400 }}
          action: upload
          app_location: polytales-fe          # 프런트 소스 위치
          output_location: build       # 빌드 산출물 위치 (npm run build 결과)
          # api_location: ""           # API 없으면 비워둠
